//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyTask.Properties.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyTask.Properties.Languages.Lang - Copy", typeof(Lang___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to goes to Sleep.
        /// </summary>
        public static string ActionStartReminder_GoesToSleep {
            get {
                return ResourceManager.GetString("ActionStartReminder.GoesToSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secound.
        /// </summary>
        public static string ActionStartReminder_Secound {
            get {
                return ResourceManager.GetString("ActionStartReminder.Secound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuts Down.
        /// </summary>
        public static string ActionStartReminder_ShutsDown {
            get {
                return ResourceManager.GetString("ActionStartReminder.ShutsDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The System.
        /// </summary>
        public static string ActionStartReminder_TitlePart1 {
            get {
                return ResourceManager.GetString("ActionStartReminder.TitlePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In: .
        /// </summary>
        public static string ActionStartReminder_TitlePart2 {
            get {
                return ResourceManager.GetString("ActionStartReminder.TitlePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will Restart.
        /// </summary>
        public static string ActionStartReminder_WillRestart {
            get {
                return ResourceManager.GetString("ActionStartReminder.WillRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Task.
        /// </summary>
        public static string AddTaskWindow_CreateTaskMainText {
            get {
                return ResourceManager.GetString("AddTaskWindow.CreateTaskMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Action.
        /// </summary>
        public static string AddTaskWindow_SetActionMainText {
            get {
                return ResourceManager.GetString("AddTaskWindow.SetActionMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Date.
        /// </summary>
        public static string AddTaskWindow_SetDateMainText {
            get {
                return ResourceManager.GetString("AddTaskWindow.SetDateMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Task Name.
        /// </summary>
        public static string AddTaskWindow_SetTaskNameMainText {
            get {
                return ResourceManager.GetString("AddTaskWindow.SetTaskNameMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Time.
        /// </summary>
        public static string AddTaskWindow_SetTimeMainText {
            get {
                return ResourceManager.GetString("AddTaskWindow.SetTimeMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By doing this, all created tasks will be stopped..
        /// </summary>
        public static string App_xaml_By_doing_this__all_created_tasks_will_be_stopped_ {
            get {
                return ResourceManager.GetString("App.xaml.By doing this, all created tasks will be stopped.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening your app.
        /// </summary>
        public static string ApplyingProcessTask_Opening_your_app {
            get {
                return ResourceManager.GetString("ApplyingProcessTask.Opening your app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Kill Apps.
        /// </summary>
        public static string ApplyingProcessTask_Start_Kill_Apps {
            get {
                return ResourceManager.GetString("ApplyingProcessTask.Start Kill Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start process of kill.
        /// </summary>
        public static string ApplyingProcessTask_start_process_of_kill {
            get {
                return ResourceManager.GetString("ApplyingProcessTask.start process of kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start process of kill apps...
        /// </summary>
        public static string ApplyingProcessTask_start_process_of_kill_apps__ {
            get {
                return ResourceManager.GetString("ApplyingProcessTask.start process of kill apps..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting process of open your exe app.
        /// </summary>
        public static string ApplyingProcessTask_Starting_process_of_open_your_exe_app {
            get {
                return ResourceManager.GetString("ApplyingProcessTask.Starting process of open your exe app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Process?.
        /// </summary>
        public static string ApplyingProcessTask_StopProcess {
            get {
                return ResourceManager.GetString("ApplyingProcessTask.StopProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Correct password:.
        /// </summary>
        public static string ChangePasswordWindow_Enter_Correct_password {
            get {
                return ResourceManager.GetString("ChangePasswordWindow.Enter Correct password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password:.
        /// </summary>
        public static string ChangePasswordWindow_Enter_new_password {
            get {
                return ResourceManager.GetString("ChangePasswordWindow.Enter new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem, your password was not changed..
        /// </summary>
        public static string ChangePasswordWindow_There_was_a_problem__your_password_was_not_changed_ {
            get {
                return ResourceManager.GetString("ChangePasswordWindow.There was a problem, your password was not changed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been successfully changed..
        /// </summary>
        public static string ChangePasswordWindow_Your_password_has_been_successfully_changed_ {
            get {
                return ResourceManager.GetString("ChangePasswordWindow.Your password has been successfully changed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your favorite theme.
        /// </summary>
        public static string ChangeThemeOfThemeUserControl_Choose_your_favorite_theme {
            get {
                return ResourceManager.GetString("ChangeThemeOfThemeUserControl.Choose your favorite theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always try.
        /// </summary>
        public static string Connection_AlwaysTry {
            get {
                return ResourceManager.GetString("Connection.AlwaysTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connection_Connect {
            get {
                return ResourceManager.GetString("Connection.Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each try time (sec).
        /// </summary>
        public static string Connection_EachTryTime {
            get {
                return ResourceManager.GetString("Connection.EachTryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string ConnectionBTN {
            get {
                return ResourceManager.GetString("ConnectionBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string DefaultTextName_AreYouSure {
            get {
                return ResourceManager.GetString("DefaultTextName.AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string DefaultTextName_Back {
            get {
                return ResourceManager.GetString("DefaultTextName.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DefaultTextName_Cancel {
            get {
                return ResourceManager.GetString("DefaultTextName.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string DefaultTextName_ChangePassword {
            get {
                return ResourceManager.GetString("DefaultTextName.ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string DefaultTextName_Confirm {
            get {
                return ResourceManager.GetString("DefaultTextName.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string DefaultTextName_Empty {
            get {
                return ResourceManager.GetString("DefaultTextName.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string DefaultTextName_Enable {
            get {
                return ResourceManager.GetString("DefaultTextName.Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string DefaultTextName_Error {
            get {
                return ResourceManager.GetString("DefaultTextName.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string DefaultTextName_Exit {
            get {
                return ResourceManager.GetString("DefaultTextName.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string DefaultTextName_Next {
            get {
                return ResourceManager.GetString("DefaultTextName.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DefaultTextName_No {
            get {
                return ResourceManager.GetString("DefaultTextName.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string defaultTextName_Open {
            get {
                return ResourceManager.GetString("defaultTextName.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucsses!.
        /// </summary>
        public static string DefaultTextName_Sucsses {
            get {
                return ResourceManager.GetString("DefaultTextName.Sucsses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful!.
        /// </summary>
        public static string DefaultTextName_Unsuccessful {
            get {
                return ResourceManager.GetString("DefaultTextName.Unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DefaultTextName_Yes {
            get {
                return ResourceManager.GetString("DefaultTextName.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD TASK.
        /// </summary>
        public static string MainPage_ADDTASK {
            get {
                return ResourceManager.GetString("MainPage.ADDTASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Minimized.
        /// </summary>
        public static string Notify_Application_Minimized {
            get {
                return ResourceManager.GetString("Notify.Application Minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Enable Tasks, application Minimized.
        /// </summary>
        public static string Notify_for_Enable_Tasks__application_Minimized {
            get {
                return ResourceManager.GetString("Notify.for Enable Tasks, application Minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me Better.
        /// </summary>
        public static string Notify_MeBetter {
            get {
                return ResourceManager.GetString("Notify.MeBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Notify_Welcome {
            get {
                return ResourceManager.GetString("Notify.Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Window.
        /// </summary>
        public static string Process_TimerWindow {
            get {
                return ResourceManager.GetString("Process.TimerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for a second.
        /// </summary>
        public static string Process_WaitingForSecound {
            get {
                return ResourceManager.GetString("Process.WaitingForSecound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string ProcessBTN {
            get {
                return ResourceManager.GetString("ProcessBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action time is behinded of system Time..
        /// </summary>
        public static string ProcessInProduct_Action_time_is_behinded_of_system_Time_ {
            get {
                return ResourceManager.GetString("ProcessInProduct.Action time is behinded of system Time.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Your Task to DataBase....
        /// </summary>
        public static string ProcessInProduct_Add_Your_Task_to_DataBase___ {
            get {
                return ResourceManager.GetString("ProcessInProduct.Add Your Task to DataBase...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding...
        /// </summary>
        public static string ProcessInProduct_Adding__ {
            get {
                return ResourceManager.GetString("ProcessInProduct.Adding..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string ProcessInProduct_AddTask {
            get {
                return ResourceManager.GetString("ProcessInProduct.AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Invalid!.
        /// </summary>
        public static string ProcessInProduct_Data_Invalid {
            get {
                return ResourceManager.GetString("ProcessInProduct.Data Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sucsess!.
        /// </summary>
        public static string ProcessInProduct_Delete_Sucsess {
            get {
                return ResourceManager.GetString("ProcessInProduct.Delete Sucsess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        public static string ProcessInProduct_Deleting___ {
            get {
                return ResourceManager.GetString("ProcessInProduct.Deleting...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error On Calulate Of Date. Please Return to Step1!.
        /// </summary>
        public static string ProcessInProduct_Error_On_Calulate_Of_Date__Please_Return_to_Step1 {
            get {
                return ResourceManager.GetString("ProcessInProduct.Error On Calulate Of Date. Please Return to Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting.
        /// </summary>
        public static string ProcessInProduct_Exiting {
            get {
                return ResourceManager.GetString("ProcessInProduct.Exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding Error...
        /// </summary>
        public static string ProcessInProduct_Finding_Error__ {
            get {
                return ResourceManager.GetString("ProcessInProduct.Finding Error..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Exit this app and disable tasks, you must unlock application.
        /// </summary>
        public static string ProcessInProduct_For_Exit_this_app_and_disable_tasks__you_must_unlock_application {
            get {
                return ResourceManager.GetString("ProcessInProduct.For Exit this app and disable tasks, you must unlock application" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value.
        /// </summary>
        public static string ProcessInProduct_Invalid_Value {
            get {
                return ResourceManager.GetString("ProcessInProduct.Invalid Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill Succesfully Canceled!.
        /// </summary>
        public static string ProcessInProduct_Kill_Succesfully_Canceled {
            get {
                return ResourceManager.GetString("ProcessInProduct.Kill Succesfully Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing your app...
        /// </summary>
        public static string ProcessInProduct_Killing_your_app__ {
            get {
                return ResourceManager.GetString("ProcessInProduct.Killing your app..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Enabled.
        /// </summary>
        public static string ProcessInProduct_Lock_Enabled {
            get {
                return ResourceManager.GetString("ProcessInProduct.Lock Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open EXE Succesfully Canceled!.
        /// </summary>
        public static string ProcessInProduct_Open_EXE_Succesfully_Canceled {
            get {
                return ResourceManager.GetString("ProcessInProduct.Open EXE Succesfully Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence of disorder.
        /// </summary>
        public static string ProcessInProduct_Presence_of_disorder {
            get {
                return ResourceManager.GetString("ProcessInProduct.Presence of disorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probably there is a problem.
        /// </summary>
        public static string ProcessInProduct_Probably_there_is_a_problem {
            get {
                return ResourceManager.GetString("ProcessInProduct.Probably there is a problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs name:.
        /// </summary>
        public static string ProcessInProduct_Programs_name {
            get {
                return ResourceManager.GetString("ProcessInProduct.Programs name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running programs that were not found:.
        /// </summary>
        public static string ProcessInProduct_Running_programs_that_were_not_found {
            get {
                return ResourceManager.GetString("ProcessInProduct.Running programs that were not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start finding...
        /// </summary>
        public static string ProcessInProduct_Start_finding__ {
            get {
                return ResourceManager.GetString("ProcessInProduct.Start finding..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting process of Kill your file...
        /// </summary>
        public static string ProcessInProduct_Starting_process_of_Kill_your_file__ {
            get {
                return ResourceManager.GetString("ProcessInProduct.Starting process of Kill your file..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action id was invalided.
        /// </summary>
        public static string ProcessInProduct_The_action_id_was_invalided {
            get {
                return ResourceManager.GetString("ProcessInProduct.The action id was invalided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The App is Locked.
        /// </summary>
        public static string ProcessInProduct_The_App_is_Locked {
            get {
                return ResourceManager.GetString("ProcessInProduct.The App is Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not open.
        /// </summary>
        public static string ProcessInProduct_The_file_does_not_open {
            get {
                return ResourceManager.GetString("ProcessInProduct.The file does not open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Task is deleted.
        /// </summary>
        public static string ProcessInProduct_The_Task_is_deleted {
            get {
                return ResourceManager.GetString("ProcessInProduct.The Task is deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These programs were successfully killed:.
        /// </summary>
        public static string ProcessInProduct_These_programs_were_successfully_killed {
            get {
                return ResourceManager.GetString("ProcessInProduct.These programs were successfully killed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This can be for a number of reasons, test that your file is closed or that the file is not closed or frozen..
        /// </summary>
        public static string ProcessInProduct_This_can_be_for_a_number_of_reasons__test_that_your_file_is_closed_or_that_the_file_is_not_closed_or_frozen_ {
            get {
                return ResourceManager.GetString("ProcessInProduct.This can be for a number of reasons, test that your file is clos" +
                        "ed or that the file is not closed or frozen.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This can have various reasons, test that your file opens or that the file has not been moved or deleted..
        /// </summary>
        public static string ProcessInProduct_This_can_have_various_reasons__test_that_your_file_opens_or_that_the_file_has_not_been_moved_or_deleted_ {
            get {
                return ResourceManager.GetString("ProcessInProduct.This can have various reasons, test that your file opens or that" +
                        " the file has not been moved or deleted.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trying to add to database...
        /// </summary>
        public static string ProcessInProduct_trying_to_add_to_database__ {
            get {
                return ResourceManager.GetString("ProcessInProduct.trying to add to database..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to conntect to database....
        /// </summary>
        public static string ProcessInProduct_Trying_to_conntect_to_database___ {
            get {
                return ResourceManager.GetString("ProcessInProduct.Trying to conntect to database...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to Exit...
        /// </summary>
        public static string ProcessInProduct_TryingToExit__ {
            get {
                return ResourceManager.GetString("ProcessInProduct.TryingToExit..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We haven&apos;t your action id.
        /// </summary>
        public static string ProcessInProduct_We_haven_t_your_action_id {
            get {
                return ResourceManager.GetString("ProcessInProduct.We haven\'t your action id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When lock is Enabled, you can&apos;t Delete a task!.
        /// </summary>
        public static string ProcessInProduct_When_lock_is_Enabled_you_can_t_Delete_a_task {
            get {
                return ResourceManager.GetString("ProcessInProduct.When lock is Enabled you can\'t Delete a task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the app is locked, you cannot change the settings.
        /// </summary>
        public static string ProcessInProduct_When_the_app_is_locked__you_cannot_change_the_settings_ {
            get {
                return ResourceManager.GetString("ProcessInProduct.When the app is locked, you cannot change the settings.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your program has been Killed.
        /// </summary>
        public static string ProcessInProduct_Your_program_has_been_Killed {
            get {
                return ResourceManager.GetString("ProcessInProduct.Your program has been Killed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your program has been opened.
        /// </summary>
        public static string ProcessInProduct_Your_program_has_been_opened {
            get {
                return ResourceManager.GetString("ProcessInProduct.Your program has been opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your task is not add to recent tasks.
        /// </summary>
        public static string ProcessInProduct_Your_task_is_not_add_to_recent_tasks {
            get {
                return ResourceManager.GetString("ProcessInProduct.Your task is not add to recent tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YourTask Is Added To Application.
        /// </summary>
        public static string ProcessInProduct_YourTask_Is_Added_To_Application {
            get {
                return ResourceManager.GetString("ProcessInProduct.YourTask Is Added To Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YourTask Is Not Added To Application.
        /// </summary>
        public static string ProcessInProduct_YourTask_Is_Not_Added_To_Application {
            get {
                return ResourceManager.GetString("ProcessInProduct.YourTask Is Not Added To Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action started at:.
        /// </summary>
        public static string RecentActionControl_ActionStartedAt {
            get {
                return ResourceManager.GetString("RecentActionControl.ActionStartedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        public static string RecentActionControl_DeleteButton {
            get {
                return ResourceManager.GetString("RecentActionControl.DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action:.
        /// </summary>
        public static string RecentActions_Action {
            get {
                return ResourceManager.GetString("RecentActions.Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Action.
        /// </summary>
        public static string RecentActions_LastAction {
            get {
                return ResourceManager.GetString("RecentActions.LastAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string S1AddTaskWindow_Day {
            get {
                return ResourceManager.GetString("S1AddTaskWindow.Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Date.
        /// </summary>
        public static string S1AddTaskWindow_EnterDate {
            get {
                return ResourceManager.GetString("S1AddTaskWindow.EnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string S1AddTaskWindow_Month {
            get {
                return ResourceManager.GetString("S1AddTaskWindow.Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string S1AddTaskWindow_Year {
            get {
                return ResourceManager.GetString("S1AddTaskWindow.Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Time.
        /// </summary>
        public static string S2AddTaskWindow_EnterTime {
            get {
                return ResourceManager.GetString("S2AddTaskWindow.EnterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string S2AddTaskWindow_Hour {
            get {
                return ResourceManager.GetString("S2AddTaskWindow.Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string S2AddTaskWindow_Minute {
            get {
                return ResourceManager.GetString("S2AddTaskWindow.Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Action.
        /// </summary>
        public static string S3AddTaskWindow_EnterAction {
            get {
                return ResourceManager.GetString("S3AddTaskWindow.EnterAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill App.
        /// </summary>
        public static string S3AddTaskWindow_KillApp {
            get {
                return ResourceManager.GetString("S3AddTaskWindow.KillApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open App.
        /// </summary>
        public static string S3AddTaskWindow_OpenFile {
            get {
                return ResourceManager.GetString("S3AddTaskWindow.OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string S3AddTaskWindow_ReStart {
            get {
                return ResourceManager.GetString("S3AddTaskWindow.ReStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut Down.
        /// </summary>
        public static string S3AddTaskWindow_ShutDown {
            get {
                return ResourceManager.GetString("S3AddTaskWindow.ShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        public static string S3AddTaskWindow_Sleep {
            get {
                return ResourceManager.GetString("S3AddTaskWindow.Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Task.
        /// </summary>
        public static string S4AddTaskWindow_DefaultTaskName {
            get {
                return ResourceManager.GetString("S4AddTaskWindow.DefaultTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Task Name.
        /// </summary>
        public static string S4AddTaskWindow_EnterTaskName {
            get {
                return ResourceManager.GetString("S4AddTaskWindow.EnterTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add task when locked app.
        /// </summary>
        public static string Security_CantAddTaskWhenLockedAppProperty {
            get {
                return ResourceManager.GetString("Security.CantAddTaskWhenLockedAppProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case of risk of penetration:.
        /// </summary>
        public static string Security_InCaseOfRiskOfPenetrationProperty {
            get {
                return ResourceManager.GetString("Security.InCaseOfRiskOfPenetrationProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Mode.
        /// </summary>
        public static string Security_LockMode {
            get {
                return ResourceManager.GetString("Security.LockMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string SecurityBTN {
            get {
                return ResourceManager.GetString("SecurityBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Applications.
        /// </summary>
        public static string SelectAppForKill_AllApplicationsButton {
            get {
                return ResourceManager.GetString("SelectAppForKill.AllApplicationsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested.
        /// </summary>
        public static string SelectAppForKill_SuggestedButton {
            get {
                return ResourceManager.GetString("SelectAppForKill.SuggestedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your application for kill.
        /// </summary>
        public static string SelectAppForKill_Title {
            get {
                return ResourceManager.GetString("SelectAppForKill.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your language:.
        /// </summary>
        public static string SelectLanguage_Select_your_language {
            get {
                return ResourceManager.GetString("SelectLanguage.Select your language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action:.
        /// </summary>
        public static string ShortActionPro_Action {
            get {
                return ResourceManager.GetString("ShortActionPro.Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created:.
        /// </summary>
        public static string ShortActionPro_DateCreated {
            get {
                return ResourceManager.GetString("ShortActionPro.DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ShortActionPro_deleteButtonTask {
            get {
                return ResourceManager.GetString("ShortActionPro.deleteButtonTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string ShortActionPro_ElementName {
            get {
                return ResourceManager.GetString("ShortActionPro.ElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date:.
        /// </summary>
        public static string ShortActionPro_StartDate {
            get {
                return ResourceManager.GetString("ShortActionPro.StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute to start action.
        /// </summary>
        public static string ShortActionPro_X_minute_to_start_action {
            get {
                return ResourceManager.GetString("ShortActionPro.X minute to start action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can control your Task in the app..
        /// </summary>
        public static string ShortActionPro_You_can_control_your_Task_in_the_app_ {
            get {
                return ResourceManager.GetString("ShortActionPro.You can control your Task in the app.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification System.
        /// </summary>
        public static string Tasks_NotificationSystem {
            get {
                return ResourceManager.GetString("Tasks.NotificationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task removal system.
        /// </summary>
        public static string tasks_Task_removal_system {
            get {
                return ResourceManager.GetString("tasks.Task removal system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning to (minute).
        /// </summary>
        public static string Tasks_WarningToMinute {
            get {
                return ResourceManager.GetString("Tasks.WarningToMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn to add task.
        /// </summary>
        public static string Tasks_WarnToAddTaskProperty {
            get {
                return ResourceManager.GetString("Tasks.WarnToAddTaskProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning when the job is running.
        /// </summary>
        public static string Tasks_WarnToClosedRunningTask {
            get {
                return ResourceManager.GetString("Tasks.WarnToClosedRunningTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent task cannot be deleted when lock mode is enabled.
        /// </summary>
        public static string tasks_WhenLockModeIsEnableWeCantDeleteRecentTask {
            get {
                return ResourceManager.GetString("tasks.WhenLockModeIsEnableWeCantDeleteRecentTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A task cannot be deleted when the lock mode is enabled.
        /// </summary>
        public static string tasks_WhenLockModeIsEnableWeCantDeleteTask {
            get {
                return ResourceManager.GetString("tasks.WhenLockModeIsEnableWeCantDeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TasksBTN {
            get {
                return ResourceManager.GetString("TasksBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Theme.
        /// </summary>
        public static string Theme_ChangeTheme {
            get {
                return ResourceManager.GetString("Theme.ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following customized themes help you have more customization capabilities..
        /// </summary>
        public static string Theme_ChangeThemeOfThemeUserControl_Subtitle1 {
            get {
                return ResourceManager.GetString("Theme_ChangeThemeOfThemeUserControl.Subtitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Theme_ChangeThemeOfThemeUserControl_ThemeBlue {
            get {
                return ResourceManager.GetString("Theme_ChangeThemeOfThemeUserControl.ThemeBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        public static string Theme_ChangeThemeOfThemeUserControl_ThemeClassic {
            get {
                return ResourceManager.GetString("Theme_ChangeThemeOfThemeUserControl.ThemeClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Theme_ChangeThemeOfThemeUserControl_ThemeYellow {
            get {
                return ResourceManager.GetString("Theme_ChangeThemeOfThemeUserControl.ThemeYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Theme_enBTN {
            get {
                return ResourceManager.GetString("Theme.enBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian.
        /// </summary>
        public static string Theme_faBTN {
            get {
                return ResourceManager.GetString("Theme.faBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Editing.
        /// </summary>
        public static string Theme_ThemeEditing {
            get {
                return ResourceManager.GetString("Theme.ThemeEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ThemeBTN {
            get {
                return ResourceManager.GetString("ThemeBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string TwoWayYesNo_Title_AreYouSure {
            get {
                return ResourceManager.GetString("TwoWayYesNo.Title.AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By performing this operation, the program will be restarted..
        /// </summary>
        public static string TwoWayYesNo_Title2_By_performing_this_operation__the_program_will_be_restarted_ {
            get {
                return ResourceManager.GetString("TwoWayYesNo.Title2.By performing this operation, the program will be restarted.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password:.
        /// </summary>
        public static string UnlockWindow_EnterPasswordText {
            get {
                return ResourceManager.GetString("UnlockWindow.EnterPasswordText", resourceCulture);
            }
        }
    }
}
